name: tasty-jenkins-xml
version: 0.1.0.0
category: Testing
synopsis: Render tasty output to XML for Jenkins (ingredient transformer)
description:
    A tasty ingredient transformer (meaning consoleTestReporter or any other
    ingredient can run as well) to output test results in XML, using the Ant
    schema. This XML can be consumed by the Jenkins continuous integration
    framework.
github: IxpertaSolutions/tasty-jenkins-xml

license: BSD3
author: Ixcom Core Team
maintainer: ixcom-core@ixperta.com
copyright: (c) 2017 Ixperta Solutions s.r.o.

extra-source-files:
    - CHANGELOG.md
    - README.md

flags:
    pedantic:
        description:
            Pass additional warning flags and -Werror to GHC.
        manual: true
        default: false

when:
    - condition: flag(pedantic)
      ghc-options:
          - -Werror
    - condition: impl(ghc >=8)
      ghc-options:
          - -Wredundant-constraints

ghc-options:
    - -Wall
    - -fwarn-tabs
    - -fwarn-implicit-prelude
    #- -fwarn-missing-import-lists

dependencies:
    - base >=4 && <5
    - tasty >= 0.10 && < 0.12

library:
    exposed-modules:
        - Test.Tasty.Runners.JenkinsXML
    source-dirs: src
    dependencies:
        - tasty-ant-xml == 1.0.*

tests:
    spec:
        main: spec.hs
        source-dirs: test
        dependencies:
            - bytestring >=0.9
            - directory >=1.2.3.0 # just >=1.2 would be ok, but tasty-ant-xml breaks with older versions yet doesn't reflect that in deps
            - hspec >=2.2
            - io-capture >=1.0
            - mockery >=0.3
            - tasty-hunit >=0.9
            - tasty-jenkins-xml
            - unix >=2

    hlint:
        main: hlint.hs
        source-dirs: test
        dependencies:
            - hlint >=1.9

tested-with: GHC==7.10.3, GHC==8.0.2
