name: tasty-jenkins-xml
version: 0.1.0.0
category: Testing
synopsis: Render tasty output to XML for Jenkins (ingredient transformer)
description:
    A tasty ingredient transformer (meaning consoleTestReporter or any other
    ingredient can run as well) to output test results in XML, using the Ant
    schema. This XML can be consumed by the Jenkins continuous integration
    framework.
github: IxpertaSolutions/tasty-jenkins-xml

license: BSD3
author: TODO
maintainer: TODO
copyright: TODO

extra-source-files:
    - CHANGELOG.md
    - README.md

ghc-options:
    - -Wall
    - -O2

dependencies:
    - base >=4 && <5
    - tasty >= 0.10 && < 0.12

library:
    exposed-modules:
        - Test.Tasty.Runners.JenkinsXML
    dependencies:
        - tasty-ant-xml == 1.0.*

tests:
    spec:
        main: Spec.hs
        source-dirs: test
        dependencies:
            - bytestring >=0.9
            - directory >=1.2
            - hspec >=2.2
            - io-capture >=1.0
            - mockery >=0.3
            - tasty-hunit >=0.9
            - tasty-jenkins-xml
            - unix >=2
